import type { Metadata } from "next";
import Link from "next/link";
import { BlogBanner, ContactSection, ServiceStrip } from "@/components/SharedSections";

export const metadata: Metadata = { title: "Shipping & Returns" };
const shipping = [["How much does shipping cost?","Shipping costs are calculated automatically at checkout based on your order and delivery address."],["Do you ship throughout New Zealand?","Yes, we ship parts throughout New Zealand, with freight costs varying depending on the item and destination."],["Do you ship internationally?","Yes, international shipping is available on selected items. Contact our team before ordering."],["How do I track my order?","Once your order has been packed and sent, tracking details can be provided so you can follow the delivery progress."],["How long will delivery take?","Delivery times vary depending on your location and parts ordered. Rural addresses and international deliveries may take longer."],["Who do I contact about shipping?","For help with shipping, delivery or tracking, contact CVT Parts Ltd at info@cvt.co.nz or 0800 288 695."]];
const returns = [["Can I return a part if I ordered the wrong item?","Most new, unopened items may be returned within 14 days. Contact us before returning anything."],["What if I receive the wrong part or a faulty item?","Contact our team as soon as possible and include your order details plus clear photos."],["Are all parts eligible for return?","No. Used, fitted, damaged or custom/special-order items may not be returnable."],["How long does a refund take?","Approved refunds can take up to 5 business days, depending on your bank or payment provider."],["What should I do before returning an item?","Contact the team first. Do not return parts without approval and a return reference."],["Who do I contact about returns?","Email info@cvt.co.nz or phone 0800 288 695."]];
function Table({rows}:{rows:string[][]}){return <table className="info-table"><tbody>{rows.map(([q,a])=><tr key={q}><th>{q}</th><td>{a}</td></tr>)}</tbody></table>}
export default function ShippingPage(){return <><section className="inner-hero shipping-hero"><div><h1>Shipping & Returns</h1><p>Need help with shipping or returns? Here is everything you need to know before and after placing your order.</p><Link className="button" href="/bearings">Find your bearing</Link></div></section><ServiceStrip/><section className="content-section"><h2>Shipping</h2><p>We offer shipping throughout New Zealand, with international delivery available on selected items.</p><Table rows={shipping}/><h2 style={{marginTop:50}}>Returns</h2><p>We accept returns on eligible new and unopened items within 14 days of delivery.</p><Table rows={returns}/></section><BlogBanner/><ContactSection/></>}
