import type { Metadata } from "next";
import Link from "next/link";
import { BlogBanner, ContactSection, ServiceStrip } from "@/components/SharedSections";

export const metadata: Metadata = { title: "Orders & Payments" };
const orders = [["Can I order online directly through the website?","Yes. Fixed-price products can be added to cart. Quote products must be confirmed by our team first."],["Do I need an account to place an order?","You can browse without an account. Sign in to retain your cart, reviews and order history."],["Can I save products for later?","Wishlist support is available to signed-in customers."],["Can I buy gift certificates?","Gift certificates are not currently available."],["What if I am unsure which part I need before ordering?","Check the product details carefully and contact us with your transmission code, vehicle model and photos."],["Can I change or cancel my order after placing it?","Contact our team as soon as possible. Changes are not guaranteed once dispatch processing begins."],["How will I know if my order has gone through?","Once payment functionality is enabled, successful orders will appear in your account and a confirmation will be sent."],["Is there a minimum order quantity?","Most products have a minimum quantity of one; any exception is shown on the product page."]];
const payments = [["What currency are prices shown in?","All website prices are shown in New Zealand dollars (NZD)."],["Are prices shown clearly before I pay?","Product prices display before checkout. Freight and the final GST treatment will be confirmed during checkout setup."],["What payment methods do you accept?","Stripe checkout will be integrated later. No live card payment is taken in this version."],["Do you offer trade or bulk pricing?","Bulk pricing is available on selected products. Submit a bulk enquiry for a tailored quote."],["Can I request a quote before paying?","Yes. Every product supports a quote enquiry, and quote-only products require one."],["Is GST included in the pricing?","The supplied catalogue tax basis requires confirmation before live checkout is enabled."],["Who do I contact about an order or payment issue?","Email info@cvt.co.nz or phone 0800 288 695."]];
function Table({rows}:{rows:string[][]}){return <table className="info-table"><tbody>{rows.map(([q,a])=><tr key={q}><th>{q}</th><td>{a}</td></tr>)}</tbody></table>}
export default function OrdersPage(){return <><section className="inner-hero orders-hero"><div><h1>Orders & Payments</h1><p>Find the key information for placing an order and paying through the CVT Bearings website.</p><Link className="button" href="/bearings">Find your bearing</Link></div></section><ServiceStrip/><section className="content-section"><h2>Orders</h2><Table rows={orders}/><h2 style={{marginTop:50}}>Payments</h2><p>Payment is intentionally disabled until Stripe and the catalogue-wide GST basis are configured.</p><Table rows={payments}/></section><BlogBanner/><ContactSection/></>}
